export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const CHANGE_MODAL_TITLE = "CHANGE_MODAL_TITLE";
export const CHANGE_MODAL_CONTENT = "CHANGE_MODAL_CONTENT";
